return {
  "nvim-treesitter/nvim-treesitter",
  event = { "BufReadPre", "BufNewFile" },
  build = ":TSUpdate",
  dependencies = {
    "windwp/nvim-ts-autotag",
  },
  main = "nvim-treesitter.config",
  opts = {
    ensure_installed = {
      "c",
      "cpp",
      "python",
      "bash",
      "lua",
      "vim",
      "vimdoc",
      "git_config",
      "gitcommit",
      "gitignore",
      "make",
      "cmake",
      'markdown',
      'markdown_inline',
    },
	autoinstall = true,
    highlight = { enable = true },
    indent = { enable = true },
    autotag = { enable = true },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = "<C-space>",
        node_incremental = "<C-space>",
        node_decremental = "<bs>",
        scope_incremental = false,
      },
    },
  },
}
